language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t rahul3vk/react-test -f ./client/Dockerfile.dev ./client/

script: 
    - docker run -e CI=true rahul3vk/react-test npm run test

after_success:
    - docker build -t rahul3vk/multi-client ./client
    - docker build -t rahul3vk/multi-nginx ./nginx
    - docker build -t rahul3vk/multi-server ./server
    - docker build -t rahul3vk/multi-worker ./worker
    # Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take the built images and push to docker hub
    - docker push rahul3vk/multi-client
    - docker push rahul3vk/multi-nginx
    - docker push rahul3vk/multi-server
    - docker push rahul3vk/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-269417613500"
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY